module.exports = {
  TK_TEXT: 1,
  TK_IF: 2,
  TK_END_IF: 3,
  TK_ELSE_IF: 4,
  TK_ELSE: 5,
  TK_EACH: 6,
  TK_END_EACH: 7,
  TK_GT: 8,
  TK_SLASH_GT: 9,
  TK_TAG_NAME: 10,
  TK_ATTR_NAME: 11,
  TK_ATTR_EQUAL: 12,
  TK_ATTR_STRING: 13,
  TK_CLOSE_TAG: 13,
  TK_EOF: 100
}
